version: '3'
services:
  nifi:
    image: nifi-test-task:latest
    build:
      context: ./
    ports:
      - "8090:8080"
      - "8095:8095"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_DATABASE_URL=jdbc:h2:./database/defaultdb
      - NIFI_DATABASE_USERNAME=nifi
      - NIFI_DATABASE_PASSWORD=nifi
